title: 実践データ科学
author: ""
logo: image/neko.png

execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/yamada-kd/binds-training/tree/main/notebook
  branch: main


sphinx:
  config:
#    language: ja
    html_show_copyright: false
    bibtex_reference_style: author_year

# HTML-specific settings
html:
  use_issues_button: false
  use_repository_button: true
  home_page_in_navbar: false
  extra_footer: |
    <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img style="0;margin-bottom:0.2em;" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a> © Copyright 2022 Graduate School of Information Sciences, Tohoku University．

launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)
  binderhub_url: ""

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
